// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaPiiti3sboftgHQYtohvZz3xm888d1Tg',
    appId: '1:199671074298:web:41726529489f8c79952843',
    messagingSenderId: '199671074298',
    projectId: 'flutter-ecommerce-app---user',
    authDomain: 'flutter-ecommerce-app---user.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app---user.firebasestorage.app',
    measurementId: 'G-40C6PNX0B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDJq9qmIKby9pkm6Lh2Zocs75qoHbcKm8',
    appId: '1:199671074298:android:ed407ed47a1d1c3f952843',
    messagingSenderId: '199671074298',
    projectId: 'flutter-ecommerce-app---user',
    storageBucket: 'flutter-ecommerce-app---user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGLsMWDhbypADvaAJvxmjA1nvfkISPQQ',
    appId: '1:199671074298:ios:1d6771f6260abb11952843',
    messagingSenderId: '199671074298',
    projectId: 'flutter-ecommerce-app---user',
    storageBucket: 'flutter-ecommerce-app---user.firebasestorage.app',
    iosBundleId: 'com.example.flutterUserEcommApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoGLsMWDhbypADvaAJvxmjA1nvfkISPQQ',
    appId: '1:199671074298:ios:1d6771f6260abb11952843',
    messagingSenderId: '199671074298',
    projectId: 'flutter-ecommerce-app---user',
    storageBucket: 'flutter-ecommerce-app---user.firebasestorage.app',
    iosBundleId: 'com.example.flutterUserEcommApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaPiiti3sboftgHQYtohvZz3xm888d1Tg',
    appId: '1:199671074298:web:f0796c76e84dd199952843',
    messagingSenderId: '199671074298',
    projectId: 'flutter-ecommerce-app---user',
    authDomain: 'flutter-ecommerce-app---user.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app---user.firebasestorage.app',
    measurementId: 'G-DVR57XH625',
  );
}
