@startuml ecommerce_sequence_diagram
title E-Commerce App - Sequence Diagram

actor User

participant ProductUI
participant CartUI
participant CheckoutUI

participant CartBloc
participant OrderBloc
participant PaymentBloc

participant Order
participant OrderItem
participant PaymentTxn

participant Backend
participant Gateway

== Add To Cart ==
User -> ProductUI : Tap "Add to Cart"
ProductUI --> CartBloc : addItem(product)
activate CartBloc
CartBloc -> CartBloc : update cart state
CartBloc --> ProductUI : update cart UI
deactivate CartBloc

== Proceed To Checkout ==
User -> CartUI : Tap "Proceed to Checkout"
CartUI -> CheckoutUI : Navigate to Checkout


== Create Order (PENDING) ==
User -> CheckoutUI : Tap "Place Order"
CheckutUI -> OrderBloc : createOrder(cartItems)
activate OrderBloc

loop For each CartItem
    OrderBloc -> OrderItem : create snapshot
    activate OrderItem
    OrderItem --> OrderBloc : orderItem
    deactivate OrderItem
end

OrderBloc -> Order : new Order(orderItems)
activate Order
Order -> Order : status = PENDING
Order -> Order : calculate totalAmount
deactivate Order

== Initiate Payment ==

User -> CheckoutUI : Confirm Payment
CheckoutUI -> PaymentBloc : initiatePayment(orderId, amount)
activate PaymentBloc

PaymentBloc -> PaymentTxn : createTransaction()
activate PaymentTxn
PaymentTxn --> PaymentBloc : clientSecretstatus = INITIATED
deactivate PaymentTxn

PaymentBloc -> Backend : requestPaymentIntent(orderId, amount)
activate Backend
Backend -> Gateway : createPaymentIntent()
activate Gateway
Gateway --> Backend : clientSecret
deactivate Gateway

Backend --> PaymentBloc : paymentIntentCreated
deactivate Backend

== User Confirms Payment ==

User -> Gateway : confirm payment (card input)
activate Gateway
Gateway --> Backend : payment result\n(APPROVED / DECLINED)
deactivate Gateway

activate Backend
Backend --> PaymentBloc : updateTransactionStatus(txnId)
deactivate Backend

== Update Order ==

alt Payment APPROVED
    PaymentBloc -> PaymentTxn : status = APPROVED
    PaymentBloc --> OrderBloc : notifySuccess(orderId)
    activate OrderBloc
    OrderBloc -> Order : markAsPaid()
    Order -> Order : status = PAID
    OrderBloc --> CheckoutUI : Show Success Message
    deactivate OrderBloc

else Payment DECLINED
    PaymentBloc -> PaymentTxn : status = DECLINED
    PaymentBloc --> OrderBloc : notifyFailure(orderId)
    activate OrderBloc
    Order -> Order : status = FAILED
    OrderBloc --> CheckoutUI : Show Failure Message
    deactivate OrderBloc
end

@enduml